# Display.
title: "The Research Software Survival Guide"
subtitle: "A brief guide for those who suddenly find themselves needing to know more"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/gvwilson/rssg/"
email: gvwilson@third-bit.com
isbn: "000-0-0000000-0"
website: "https://gvwilson.github.io/rssg/"
purchase: "http://FIXME"
paypal: "https://paypal.me/gvwilson/10CAD"

# Theme color.
background: "#e0f0e0"

# Code highlighting.
highlighter: rouge

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- requirements.txt
- tex_en

# Markers in generated files.
marker:
  start: "<!-- main start -->"
  end: "<!-- main end -->"
  crossref: "let CROSSREF="

# Collections: one for lessons and one for extras for each language suffix.
collections:
  chapters_en:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: chapters_en
    values:
      language: "en"
      layout: "default"

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /project/
  - /versioning/
  - /hosting/
  - /automation/
  - /robust/
  - /issues/
  - /license/
  - /packaging/
  - /review/
  - /testing/
  - /continuous/
  - /agile/
  - /sturdy/
  - /tdd/
  - /compromise/
  - /community/
  - /mentor/
  - /governance/
  - /marketing/
  - /finale/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /bib/
  - /gloss/
  - /guide/

# Translations by language.
translations:
  en:
    generated: "Last generated"
    objectives: "After reading this chapter, you will be able to..."
