# Display.
title: "The Research Software Survival Guide"
subtitle: "A brief guide for those who suddenly find themselves needing to know more"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/gvwilson/rssg/"
email: gvwilson@third-bit.com
isbn: "000-0-0000000-0"
website: "https://gvwilson.github.io/rssg/"
purchase: ""
paypal: ""

# Theme color.
background: "#e0f0e0"

# Jekyll settings.
highlighter: rouge
plugins:
  - "jekyll-redirect-from"

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- misc
- requirements.txt
- tex_en

# Markers in generated files.
marker:
  start: "<!-- main start -->"
  end: "<!-- main end -->"
  crossref: "let CROSSREF="

# Collections: one for lessons and one for extras for each language suffix.
collections:
  chapters_en:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: chapters_en
    values:
      language: "en"
      layout: "default"

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /rse/
  - /layout/
  - /versioning/
  - /hosting/
  - /data/
  - /automation/
  - /robust/
  - /issues/
  - /licensing/
  - /packaging/
  - /review/
  - /testing/
  - /continuous/
  - /publishing/
  - /agile/
  - /sturdy/
  - /tdd/
  - /compromise/
  - /community/
  - /mentor/
  - /governance/
  - /marketing/
  - /finale/
  bib:
  - /bib/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /gloss/
  - /guide/

# Translations by language.
translations:
  en:
    generated: "Last generated"
    keypoints: "Key points"
    objectives: "Learning objectives"
    questions: "Questions answered"
    singlepage: "Single page version"
