# Display.
title: "Set On Fire"
subtitle: "How to Create a Research Software Commons"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/merely-useful/set-on-fire/"
email: gvwilson@third-bit.com
isbn: "000-0-0000000-0"
website: "https://merely-useful.github.io/set-on-fire/"
purchase: ""
paypal: ""
organization: https://merely-useful.github.io/

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /hosting/
  - /licensing/
  - /provenance/
  - /packaging/
  - /review/
  - /process/
  - /community/
  - /mentor/
  - /governance/
  - /marketing/
  - /finale/
  bib:
  - /bib/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /gloss/
  - /guide/

# Theme color.
background: "#f0f0fa"

# Jekyll settings.
highlighter: rouge
plugins:
  - "jekyll-redirect-from"

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- misc
- requirements.txt
- src
- tex
- unused

# Markers in generated files.
marker:
  start: "<!-- main start -->"
  end: "<!-- main end -->"
  crossref: "let CROSSREF="

# Collections: one for lessons and one for extras for each language suffix.
collections:
  en:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: en
    values:
      language: "en"
      layout: "default"

# Translations by language.
translations:
  en:
    generated: "Last generated"
    keypoints: "Key points"
    objectives: "Learning objectives"
    questions: "Questions answered"
    singlepage: "Single page version"
